version: "3"
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: proxy_db
    volumes:
      - .docker-data/postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: leshka99514@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"